import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { MenuList } from "./_components/MenuList";
import { MainComp } from "./_utils/MainComp";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainComp></MainComp>
        <MenuList></MenuList>
        {children}
      </body>
    </html>
  );
}
